sonar.projectKey=FranmVeera_gestor-gastos
sonar.organization=franmveera

sonar.sources=frontend/src,backend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.test.js,**/*.test.jsx,**/*.test.mjs

sonar.coverage.exclusions=**

sonar.sourceEncoding=UTF-8