sonar.projectKey=FranmVeera_gestor-gastos
sonar.organization=franmveera

sonar.sources=frontend/src,backend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**

sonar.sourceEncoding=UTF-8