sonar.projectKey=FranmVeera_gestor-gastos
sonar.organization=franmveera

sonar.projectName=gestor-gastos

sonar.sources=frontend/src,backend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.test.js,**/*.test.jsx,**/*.test.mjs

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.coverage.exclusions=**

sonar.sourceEncoding=UTF-8